### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by Blomus** [ludiazv/node-red-contrib-nrf24#6]
After Installing the nrf24 package I have the following error message.
Can someone help me with this problem?

Error: Could not locate the bindings file. Tried: → /home/pi/.node-red/node_modules/nrf24/build/nRF24.node → /home/pi/.node-red/node_modules/nrf24/build/Debug/nRF24.node → /home/pi/.node-red/node_modules/nrf24/build/Release/nRF24.node → /home/pi/.node-red/node_modules/nrf24/out/Debug/nRF24.node → /home/pi/.node-red/node_modules/nrf24/Debug/nRF24.node → /home/pi/.node-red/node_modules/nrf24/out/Release/nRF24.node → /home/pi/.node-red/node_modules/nrf24/Release/nRF24.node → /home/pi/.node-red/node_modules/nrf24/build/default/nRF24.node → /home/pi/.node-red/node_modules/nrf24/compiled/12.17.0/linux/arm/nRF24.node → /home/pi/.node-red/node_modules/nrf24/addon-build/release/install-root/nRF24.node → /home/pi/.node-red/node_modules/nrf24/addon-build/debug/install-root/nRF24.node → /home/pi/.node-red/node_modules/nrf24/addon-build/default/install-root/nRF24.node → /home/pi/.node-red/node_modules/nrf24/lib/binding/node-v72-linux-arm/nRF24.node (line:5)

**Comment by ludiazv** [comment]
Hi,
Could provide additional detail of your setup: OS, Nodejs version, installation method?

Regards,

**Comment by Blomus** [comment]
Hi ludiazv,
thank you for your answer.
- Raspberry Pi 4 Model B Rev
- OS: Linux raspberrypi 4.19.118-v7l+
- Nodejs version:12.17.0-1nodesource1
- Installation method: First I tried to install the package via node-red. But this was never completed successfully. Then I installed the package using the following terminal command.
_npm install node-red-contrib-nrf24_

regards

**Comment by Blomus** [comment]
Maybe, this error can help you, too.
home/pi/.cache/node-gyp/12.17.0/include/node/v8.h:3135:5: note:   candidate expects 2 arguments, 1 provided
make: *** [nRF24.target.mk:135: Release/obj.target/nRF24/rf24_util.o] Fehler 1
make: Verzeichnis „/home/pi/node_modules/node-red-contrib-nrf24/node_modules/nrf24/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.118-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node_modules/node-red-contrib-nrf24/node_modules/nrf24
gyp ERR! node -v v12.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nrf24@0.0.0-alpha4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nrf24@0.0.0-alpha4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ludiazv** [comment]
I think the problem is node v12. Current version in npm doesn't with this version. :(

The fix is not still available. But I hope to find some time to implement the fix.

**Comment by ludiazv** [comment]
#4

**Comment by ludiazv** [comment]
Now the module is compatible with node 12 & 14
